# Generated by Django 4.0.4 on 2022-05-18 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, verbose_name='도시')),
                ('street', models.CharField(max_length=64, verbose_name='도로명 주소')),
                ('zipcode', models.CharField(max_length=32, verbose_name='우편번호')),
                ('status', models.CharField(choices=[('R', 'Ready'), ('C', 'Comp')], default='R', max_length=2, verbose_name='배달 상태')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='주문 시간')),
                ('status', models.CharField(choices=[('O', 'Order'), ('C', 'Cancel')], default='O', max_length=2)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.delivery')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.IntegerField(verbose_name='구매 가격')),
                ('count', models.IntegerField(verbose_name='구매 수량')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
