# Generated by Django 4.0.4 on 2022-05-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default='', max_length=64, verbose_name='도시'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='street',
            field=models.CharField(default='', max_length=64, verbose_name='도로명 주소'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='zipcode',
            field=models.CharField(default='', max_length=32, verbose_name='우편번호'),
            preserve_default=False,
        ),
    ]
