# 정적 파일이 위치하는 서버에 backports-zoneinfo 패키지를 추가로 설치한다 -> poetry add --no-dev backports-zoneinfo
# 미 설치시 collectstatic 명령이 안된다.

name: Docker Image CI

on:
  push:
    branches: [ feature/CI_CD_설정 ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Set Poetry config
        run: |
          poetry config settings.virtualenvs.in-project false
          poetry config settings.virtualenvs.path ~/.virtualenvs

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Code Quality
        run: poetry run black . --check

      - name: Test with pytest
        #        env:
        #          DJANGO_SETTINGS_MODULE: project.settings
        #          SECRETS_FILE: .confidential/ci.json
        run: poetry run ./manage.py --settings=shop_django.settings.dev
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }} 
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/shop:${GITHUB_SHA::7}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/shop:${GITHUB_SHA::7}
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master  # docs: https://github.com/marketplace/actions/ssh-remote-commands?version=v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        envs: GITHUB_SHA
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/shop:${GITHUB_SHA::7}
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/shop:${GITHUB_SHA::7} shop_api
          docker stop server 
          docker run -d --rm --name server -p 8000:8000 \
            -e DJANGO_SETTINGS_MODULE=shop_django.settings.prod \
            -e DB_USER="${{ secrets.DB_USER }}" \
            -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_PORT="${{ secrets.DB_PORT }}" \
            -e STATIC_ROOT="${{ secrets.STATIC_ROOT }}" \
            -e SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" shop_api
          cd ~/Projects/shop_api_django
          git pull
          /home/paul/.pyenv/shims/python manage.py collectstatic --settings=shop_django.settings.collectstatic --no-input
