name: Docker Image CI

on:
  push:
    branches: [ feature/CI_CD_설정 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }} 
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/shop:${GITHUB_SHA::7}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/shop:${GITHUB_SHA::7}
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master  # docs: https://github.com/marketplace/actions/ssh-remote-commands?version=v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        envs: GITHUB_SHA
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/shop:${GITHUB_SHA::7}
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/shop:${GITHUB_SHA::7} shop_api
          docker stop server 
          docker run -d --rm --name server -p 8000:8000 -e {{ secrets.DJANGO_SECRET_KEY }} shop_api